# Generated by Django 6.0.5 on 2026-05-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente_nome',
            field=models.CharField(default='Provisório', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_agendada',
            field=models.DateTimeField(default='Provisório2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber_grid.servico'),
        ),
    ]
