# Generated by Django 6.1.1 on 2026-10-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0002_bloqueiohorario_horariodefuncionamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariodefuncionamento',
            old_name='dia_semana',
            new_name='dia_fim',
        ),
        migrations.AddField(
            model_name='horariodefuncionamento',
            name='dia_inicio',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Segunda-Feira'), (1, 'Terça-Feira'), (2, 'Quarta-Feira'), (3, 'Quinta-Feira'), (4, 'Sexta-Feira'), (5, 'Sábado'), (6, 'Domingo')], default=1),
            preserve_default=False,
        ),
    ]
