# Generated by Django 6.1 on 2026-08-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0002_alter_agendamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barber_grid.cliente'),
        ),
    ]
