# Generated by Django 6.1 on 2026-08-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0003_alter_agendamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
