# Generated by Django 6.1.1 on 2026-10-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0003_rename_dia_semana_horariodefuncionamento_dia_fim_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('data', 'horario'), name='unico_agendamento'),
        ),
    ]
