# Generated by Django 6.1 on 2026-08-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0004_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateField(),
        ),
    ]
