# Generated by Django 6.1 on 2026-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0004_agendamento_unico_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20),
        ),
    ]
