# Generated by Django 6.0.6 on 2026-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0005_agendamento_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='unico_agendamento',
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelado'), _negated=True), fields=('data', 'horario'), name='unico_agendamento_ativo'),
        ),
    ]
