# Generated by Django 6.1 on 2026-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0005_alter_agendamento_data_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_cliente', 'sobrenome_cliente']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome_cliente',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone ou contato'),
        ),
    ]
