# Generated by Django 6.1 on 2026-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0006_remove_agendamento_unico_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
