# Generated by Django 6.1 on 2026-08-29 14:20

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0007_cliente_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome_servico']},
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(
                default=30,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Duração estimada (minutos)',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
            ),
        ),
    ]
