# Generated by Django 6.1 on 2026-08-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0008_servico_duracao_minutos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_agendamento', '-horario_agendamento']},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(
                choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado')],
                default='pendente',
                max_length=20,
            ),
        ),
    ]
