# Generated by Django 6.1 on 2026-09-01 12:06

import barber_grid.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_grid', '0009_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendamento',
            field=models.TimeField(default=barber_grid.models.horario_atual),
        ),
    ]
